/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import fuzzy2.Deffuzification;
import fuzzy2.CompensatoryAnd;
import fuzzy2.Type2CompensatoryAnd;
import fuzzy2.Type2Deffuzification;
import fuzzy2.YagersMinMax;
import javax.swing.DefaultListModel;
/**
 *
 * @author bamo
 */
public class CompensatoryAndForm extends javax.swing.JFrame {

    /**
     * Creates new form CompensatoryAndForm
     */
    public CompensatoryAndForm() {
        initComponents();
        loadType1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fuzzyType = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        andSet2List = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        secondAndSetList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        secondAndSet2List = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        finalAndSet = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        andSetList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compensatory And");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel6.setText("Fuzzy Logic Type");

        fuzzyType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Type 1", "Type 2" }));
        fuzzyType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fuzzyTypeItemStateChanged(evt);
            }
        });
        fuzzyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuzzyTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(fuzzyType, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fuzzyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        jScrollPane1.setViewportView(andSet2List);

        jScrollPane2.setViewportView(secondAndSetList);

        jScrollPane3.setViewportView(secondAndSet2List);

        jScrollPane4.setViewportView(finalAndSet);

        jScrollPane5.setViewportView(andSetList);

        jLabel7.setText("And Set one");

        jLabel8.setText("And Set two");

        jLabel9.setText("Second and set one");

        jLabel10.setText("Second and set two");

        jLabel11.setText("Final set");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fuzzyTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fuzzyTypeItemStateChanged
        // TODO add your handling code here:
        if (fuzzyType.getSelectedIndex() == 0) {
            loadType1();
        } else {
            loadType2();
        }

    }//GEN-LAST:event_fuzzyTypeItemStateChanged

    private void fuzzyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuzzyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuzzyTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompensatoryAndForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompensatoryAndForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompensatoryAndForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompensatoryAndForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CompensatoryAndForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList andSet2List;
    private javax.swing.JList andSetList;
    private javax.swing.JList finalAndSet;
    private javax.swing.JComboBox fuzzyType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList secondAndSet2List;
    private javax.swing.JList secondAndSetList;
    // End of variables declaration//GEN-END:variables

    private void loadType1() {
        CompensatoryAnd.centroidDef = Deffuzification.centroidDef;
        CompensatoryAnd cAnd = new CompensatoryAnd();
        double  [][]normalisedyagersWeightedDecisionMatrix =cAnd.calculateNormalisedYagersWeightedDecisionMatrix();
        double [] set1 =cAnd.firstMultiplicationSet();
        double [] set2 = cAnd.overallPowerOfEachAlternative();
        double [] set3 = cAnd.SecondMultiplicationSet();
        double [] set4 = cAnd.overallPowerOfSecondSetOfEachAlternative();
        double [] finalSet = cAnd.finalCompensatoryValue();
        andSet2List.removeAll();
        andSetList.removeAll();
        secondAndSet2List.removeAll();
        secondAndSetList.removeAll();
        finalAndSet.removeAll();
        DefaultListModel one = new DefaultListModel();
        for (int i = 0; i < set1.length; i++) {
            one.addElement(""+set1[i]);
        }
        andSetList.setModel(one);
        DefaultListModel two = new DefaultListModel();
        for (int i = 0; i < set2.length; i++) {
            two.addElement(""+set2[i]);
        }
        andSet2List.setModel(two);
        
        DefaultListModel three = new DefaultListModel();
        for (int i = 0; i < set3.length; i++) {
            three.addElement(""+set3[i]);
        }
        secondAndSetList.setModel(three);
       DefaultListModel four = new DefaultListModel();
        for (int i = 0; i < set4.length; i++) {
            four.addElement(""+set4[i]);
        }
        secondAndSet2List.setModel(four);
        
        DefaultListModel five = new DefaultListModel();
        for (int i = 0; i < finalSet.length; i++) {
            five.addElement(""+finalSet[i]);
        }
        finalAndSet.setModel(five);
    }

    private void loadType2() {
        Type2CompensatoryAnd.centroidDef = Type2Deffuzification.centroidDef;
        Type2CompensatoryAnd cAnd = new Type2CompensatoryAnd();
        double [] set1 =cAnd.firstMultiplicationSet();
        double [] set2 = cAnd.overallPowerOfEachAlternative();
        double [] set3 = cAnd.SecondMultiplicationSet();
        double [] set4 = cAnd.overallPowerOfSecondSetOfEachAlternative();
        double [] finalSet = cAnd.finalCompensatoryValue();
        andSet2List.removeAll();
        andSetList.removeAll();
        secondAndSet2List.removeAll();
        secondAndSetList.removeAll();
        finalAndSet.removeAll();
        DefaultListModel one = new DefaultListModel();
        for (int i = 0; i < set1.length; i++) {
            one.addElement(""+set1[i]);
        }
        andSetList.setModel(one);
        DefaultListModel two = new DefaultListModel();
        for (int i = 0; i < set2.length; i++) {
            two.addElement(""+set2[i]);
        }
        andSet2List.setModel(two);
        
        DefaultListModel three = new DefaultListModel();
        for (int i = 0; i < set3.length; i++) {
            three.addElement(""+set3[i]);
        }
        secondAndSetList.setModel(three);
       DefaultListModel four = new DefaultListModel();
        for (int i = 0; i < set4.length; i++) {
            four.addElement(""+set4[i]);
        }
        secondAndSet2List.setModel(four);
        
        DefaultListModel five = new DefaultListModel();
        for (int i = 0; i < finalSet.length; i++) {
            five.addElement(""+finalSet[i]);
        }
        finalAndSet.setModel(five);

    }
}
